version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev
    container_name: api
    env_file:
      - ../env-dev
    volumes:
      - ../:/usr/src/mymaven
    ports:
      - "8080:8080"
  db:
    container_name: postgres
    image: postgres
    env_file:
      - ../env-dev
    ports:
      - "5432:5432"